#!/bin/bash

# this script must be called from parent directory

../grammar/waxeye/bin/waxeye -g javascript ../js/build ../grammar/adabru_markup.waxeye &
../grammar/waxeye/bin/waxeye -i ../grammar/adabru_markup.waxeye < ./markup/test.md | less
